version: '3.6'
services:
  mysql:
    # Uncomment the below line for m1 macs
    # platform: linux/x86_64
    image: mysql:8.0
    # image: mariadb:10.9.5
    container_name: ${APP_NAME}-mysql
    volumes:
      - ./db:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  php:
    depends_on: 
      - mysql
    image: php-local
    build: ../docker/php
    ports:
      - 80:80
    container_name: ${APP_NAME}-php
    restart: always
    volumes: 
      - ./basic_php_project:/var/www/html

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}-phpmyadmin
    environment:
      PMA_HOST: "${DB_HOST}"
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '8080:80'
    links:
      - mysql:mysql
